version: "3.9"

services:
  app:
    build: .
    container_name: login_app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/studentDB
      - SESSION_SECRET=change_me_for_production
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: login_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
